export const listUser = [
  {
    key: '1',
    id: '1',
    nameStudent: 'Trần Quang Đạo',
    codeClass: 'PTTKHT/01',
    subject: 'Phân tích thiết kế hệ thống',
    note: 'Xem chi tiết',
    time: 'Thứ tư hàng tuần',
    numberoflessonslaeared: '2',
    location: 'Nhà abc phố bcd',
    cost: '10.000.000 VND',
    phonenuberstudent: '0824216169',
    email: 'tranquangdao16092002@gmail.com',
    dateofbirth: '16/09/2002'
  },
  {
    key: '2',
    id: '2',
    nameStudent: 'Ngô Hải Văn',
    codeClass: 'PTTKHT/02',
    subject: 'Phân tích thiết kế hệ thống',
    note: 'Xem chi tiết',
    time: 'Thứ tư hàng tuần',
    numberoflessonslaeared: '2',
    location: 'Nhà abc phố bcd',
    cost: '10.000.000 VND',
    phonenuberstudent: '0824216169',
    email: 'tranquangdao16092002@gmail.com',
    dateofbirth: '16/09/2002'
  },
  {
    key: '3',
    id: '3',
    nameStudent: 'Bùi Ngọc Thành',
    codeClass: 'PTTKHT/03',
    subject: 'Phân tích thiết kế hệ thống',
    note: 'Xem chi tiết',
    time: 'Thứ tư hàng tuần',
    numberoflessonslaeared: '2',
    location: 'Nhà abc phố bcd',
    cost: '10.000.000 VND',
    phonenuberstudent: '0824216169',
    email: 'tranquangdao16092002@gmail.com',
    dateofbirth: '16/09/2002'
  },
  {
    key: '4',
    id: '4',
    nameStudent: 'Hồ Anh Trí',
    codeClass: 'PTTKHT/04',
    subject: 'Phân tích thiết kế hệ thống',
    note: 'Xem chi tiết',
    time: 'Thứ tư hàng tuần',
    numberoflessonslaeared: '2',
    location: 'Nhà abc phố bcd',
    cost: '10.000.000 VND',
    phonenuberstudent: '0824216169',
    email: 'tranquangdao16092002@gmail.com',
    dateofbirth: '16/09/2002'
  },
  {
    key: '5',
    id: '5',
    nameStudent: 'Nguyễn Hữu Truyền',
    codeClass: 'PTTKHT/05',
    subject: 'Phân tích thiết kế hệ thống',
    note: 'Xem chi tiết',
    time: 'Thứ tư hàng tuần',
    numberoflessonslaeared: '2',
    location: 'Nhà abc phố bcd',
    cost: '10.000.000 VND',
    phonenuberstudent: '0824216169',
    email: 'tranquangdao16092002@gmail.com',
    dateofbirth: '16/09/2002'
  }
]
export const listTutor = [
  {
    key: '1',
    id: '1',
    nameStudent: 'Trần Quang Đạo',
    codeClass: 'PTTKHT/01',
    subject: 'Phân tích thiết kế hệ thống',
    note: 'Xem chi tiết',
    time: 'Thứ tư hàng tuần',
    numberoflessonslaeared: '2',
    location: 'Nhà abc phố bcd',
    cost: '10.000.000 VND',
    phonenuberstudent: '0824216169',
    email: 'tranquangdao16092002@gmail.com',
    dateofbirth: '16/09/2002'
  },
  {
    key: '2',
    id: '2',
    nameStudent: 'Ngô Hải Văn',
    codeClass: 'PTTKHT/02',
    subject: 'Phân tích thiết kế hệ thống',
    note: 'Xem chi tiết',
    time: 'Thứ tư hàng tuần',
    numberoflessonslaeared: '2',
    location: 'Nhà abc phố bcd',
    cost: '10.000.000 VND',
    phonenuberstudent: '0824216169',
    email: 'tranquangdao16092002@gmail.com',
    dateofbirth: '16/09/2002'
  },
  {
    key: '3',
    id: '3',
    nameStudent: 'Bùi Ngọc Thành',
    codeClass: 'PTTKHT/03',
    subject: 'Phân tích thiết kế hệ thống',
    note: 'Xem chi tiết',
    time: 'Thứ tư hàng tuần',
    numberoflessonslaeared: '2',
    location: 'Nhà abc phố bcd',
    cost: '10.000.000 VND',
    phonenuberstudent: '0824216169',
    email: 'tranquangdao16092002@gmail.com',
    dateofbirth: '16/09/2002'
  },
  {
    key: '4',
    id: '4',
    nameStudent: 'Hồ Anh Trí',
    codeClass: 'PTTKHT/04',
    subject: 'Phân tích thiết kế hệ thống',
    note: 'Xem chi tiết',
    time: 'Thứ tư hàng tuần',
    numberoflessonslaeared: '2',
    location: 'Nhà abc phố bcd',
    cost: '10.000.000 VND',
    phonenuberstudent: '0824216169',
    email: 'tranquangdao16092002@gmail.com',
    dateofbirth: '16/09/2002'
  },
  {
    key: '5',
    id: '5',
    nameStudent: 'Nguyễn Hữu Truyền',
    codeClass: 'PTTKHT/05',
    subject: 'Phân tích thiết kế hệ thống',
    note: 'Xem chi tiết',
    time: 'Thứ tư hàng tuần',
    numberoflessonslaeared: '2',
    location: 'Nhà abc phố bcd',
    cost: '10.000.000 VND',
    phonenuberstudent: '0824216169',
    email: 'tranquangdao16092002@gmail.com',
    dateofbirth: '16/09/2002'
  }
]
export const leverDocuments = [
  {
    EASY: 'Dễ',
    MEDIUM: 'trung bình',
    HARD: 'Khó'
  }
]
